import { Ad50Logo, CtaIcon, news } from "../shared";
import { CorporateFooter, CorporateHeader } from "./corporate-shell";
import type { CSSProperties } from "react";

const services = [
  ["01", "Atracción de talento", "Head Hunting, reclutamiento y selección, evaluación por competencias y evaluación de potencial."],
  ["02", "Desarrollo de personas", "Capacitación OTEC, coaching, formación de líderes y academias corporativas a la medida."],
  ["03", "Gestión de carrera", "Outplacement, mentoring y acompañamiento experto para transiciones y movilidad profesional."],
  ["04", "Transformación organizacional", "Gestión del cambio, equipos de alto desempeño, cultura, liderazgo e integración generacional."],
];

const method = [
  ["01", "Escuchamos", "Comprendemos el desafío, el contexto y los resultados que la organización necesita."],
  ["02", "Diseñamos", "Construimos una solución a la medida, con objetivos, alcance y metodología claros."],
  ["03", "Implementamos", "Activamos el proceso con un equipo senior y seguimiento cercano."],
  ["04", "Acompañamos", "Medimos, ajustamos y permanecemos presentes hasta consolidar el resultado."],
];

const spectrumTopHeights = [28, 36, 44, 52, 60, 68, 76, 84, 92, 100, 92, 84, 76, 68, 60, 52, 44, 36, 28];
const talentProfiles = [
  ["CM", "Liderazgo", "Estrategia · Equipos · Cultura"],
  ["AP", "Operaciones", "Procesos · Gestión · Mejora"],
  ["FS", "Tecnología", "Datos · Producto · Innovación"],
  ["MG", "Comercial", "Crecimiento · Clientes · Negocio"],
  ["VR", "Personas", "Talento · Desarrollo · Cambio"],
  ["JL", "Finanzas", "Control · Planificación · Riesgo"],
];

export default function Corporativa() {
  return <main className="corp-site">
    <CorporateHeader />
    <section className="corp-hero" id="inicio"><div className="corp-shell"><p className="corp-eyebrow">Desarrollamos talento. Transformamos organizaciones.</p><div className="corp-lead"><h1>Soluciones estratégicas para el talento que genera <span>valor.</span></h1><div><p>Más de 15 años acompañando a organizaciones para atraer, desarrollar e integrar a las personas que impulsan sus resultados.</p><a className="corp-button" href="#servicios">Conoce nuestros servicios</a></div></div><div className="corp-team"><div><span>Somos AD Consulting</span><b>Experiencia que entiende tu desafío</b></div><img src="/equipo-ad-consulting.jpg" alt="Equipo completo de AD Consulting" /></div><div className="corp-proof"><p><strong>+100 empresas</strong><span>han confiado en AD</span></p><p><strong>30+ ciudades</strong><span>con cobertura nacional</span></p><p><strong>25+ años</strong><span>liderando personas</span></p></div></div></section>
    <section className="corp-video-section" aria-labelledby="corp-video-title"><div className="corp-shell"><div className="corp-video-heading"><p className="corp-eyebrow">Conoce AD Consulting</p><h2 id="corp-video-title">Personas que potencian <span>personas.</span></h2></div><div className="corp-video-frame"><video controls muted playsInline preload="metadata" poster="/video-ad-consulting-poster.webp" aria-label="Video corporativo de AD Consulting"><source src="https://www.adconsulting.cl/video_ad_2025.mp4" type="video/mp4" />Tu navegador no soporta la reproducción de video.</video></div></div></section>
    <section className="corp-challenge"><div className="corp-shell"><p className="corp-eyebrow">El desafío</p><div><h2>Encontrar, desarrollar y retener talento <span>nunca fue tan difícil.</span></h2><p>Escasez de candidatos. Rotación que cuesta caro. Líderes que necesitan crecer. Generaciones distintas que deben trabajar juntas. Y todo, a la velocidad del negocio.</p><blockquote>Gestionar personas ya no basta. Lo sabemos porque conocemos el mercado.</blockquote></div></div></section>
    <section className="corp-spectrum" aria-labelledby="corp-spectrum-title"><div className="corp-shell"><div className="corp-spectrum-copy"><p className="corp-eyebrow">Una mirada integral</p><h2 id="corp-spectrum-title">El talento no se gestiona por partes. <span>Se activa como un sistema.</span></h2><p>Atracción, desarrollo, carrera y transformación trabajando en una misma dirección.</p></div><div className="corp-spectrum-visual" aria-hidden="true">{spectrumTopHeights.map((height,index)=><span className="corp-spectrum-bar" key={`${height}-${index}`} data-bar-top={100-height} style={{"--bar-index":index} as CSSProperties} />)}</div></div></section>
    <section className="corp-services corp-services-spectrum corp-shell" id="servicios"><p className="corp-eyebrow">Lo que hacemos</p><h2>Soluciones que conectan estrategia, personas y <span>resultados.</span></h2><div className="corp-service-grid">{services.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><a href="/corporativa/servicios">Conocer más <CtaIcon /></a></article>)}</div></section>
    <section className="corp-talent-flow" aria-labelledby="talent-flow-title"><div className="corp-shell"><div className="corp-talent-copy"><p className="corp-eyebrow">Perfiles en movimiento</p><h2 id="talent-flow-title">Cada trayectoria cuenta. Encontramos la que <span>mueve tu organización.</span></h2><p>Leemos más que un currículum: conectamos experiencia, potencial y cultura con el desafío que tu empresa necesita resolver.</p><a className="corp-text-link" href="/corporativa/servicios">Conoce nuestro proceso de selección <CtaIcon /></a></div><div className="corp-resume-stage" aria-label="Representación animada de perfiles profesionales">{talentProfiles.map(([initials,area,skills],index)=><article className="corp-resume-sheet" key={initials} style={{animationDelay:`${index*2.5}s`}}><div className="corp-resume-head"><span>{initials}</span><div><b>Perfil profesional</b><small>{area}</small></div></div><i /><i /><i className="corp-resume-line-short" /><div className="corp-resume-skills"><span /><span /><span /></div><p>{skills}</p></article>)}</div></div><div className="corp-brand-marquee" aria-label="Ecosistema de marcas AD Consulting"><div className="corp-brand-track">{[0,1].map((set)=><div className="corp-brand-set" aria-hidden={set===1} key={set}><img src="/ad-consulting-logo-dark.png" alt={set===0?"AD Consulting":""} /><strong>AD BLACK</strong><img src="/ad50-logo-dark.png" alt={set===0?"AD+50 Talento Senior":""} /><strong>OTEC AD</strong><span>GESTIÓN DE CARRERA</span><span>DESARROLLO DE PERSONAS</span></div>)}</div></div></section>
    <section className="corp-method"><div className="corp-shell"><p className="corp-eyebrow">Nuestra forma de trabajar</p><h2>Escuchamos primero. Acompañamos <span>hasta el resultado.</span></h2><svg className="corp-method-path" viewBox="0 0 1000 180" preserveAspectRatio="none" aria-hidden="true"><path d="M18 126 C120 34 205 154 308 82 S500 32 594 105 S788 156 982 45" /></svg><div className="corp-method-grid">{method.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="corp-intro corp-shell" id="nosotros"><div><p className="corp-eyebrow">Quiénes somos</p><h2>Más de 25 años liderando personas, <span>no solo asesorándolas.</span></h2></div><div><p>Nuestros socios lideraron áreas de Recursos Humanos y desarrollo de personas dentro de empresas de distintos sectores.</p><p>Entendemos tu desafío porque lo vivimos. Combinamos experiencia, actualización constante y una mirada práctica para diseñar soluciones que funcionan.</p><a className="corp-text-link" href="/corporativa/nosotros">Conoce a nuestro equipo <CtaIcon /></a></div></section>
    <section className="corp-routes"><div className="corp-shell"><p className="corp-eyebrow">¿Qué necesitas?</p><h2>Un punto de entrada para <span>cada persona.</span></h2><div className="corp-route-grid"><article><span>Para las Empresas</span><h3>Busco talento para mi organización</h3><p>Selección, liderazgo, transición laboral y capacitación.</p><a href="/corporativa/servicios">Explorar servicios <CtaIcon /></a></article><article><span>Para las Personas</span><h3>Busco una nueva oportunidad</h3><p>Conoce el proceso y las ofertas actualmente disponibles.</p><a href="https://adconsulting.trabajando.cl/">Ver ofertas <CtaIcon /></a></article><article><span>Para los Equipos</span><h3>Quiero capacitar a mi organización</h3><p>Programas flexibles desarrollados por una OTEC reconocida por SENCE.</p><a href="/corporativa/servicios">Conocer capacitaciones <CtaIcon /></a></article></div></div></section>
    <section className="corp-platform" id="ad50"><div className="corp-shell"><div><p className="corp-eyebrow">Una plataforma de AD Consulting</p><Ad50Logo tone="light" /><h2>La experiencia se activa con <span>oportunidades reales.</span></h2><p>Conecta talento senior y organizaciones a través de empleabilidad, formación, reclutamiento e integración generacional.</p><a className="corp-button" href="/corporativa/ad50">Conocer AD+50 <CtaIcon /></a></div><img src="https://ad50.adconsulting.cl/images/ad50-quienes-somos-equipo.webp" alt="Profesionales de distintas generaciones colaborando" /></div></section>
    <section className="corp-news corp-shell" id="actualidad"><p className="corp-eyebrow">Actualidad AD Consulting</p><h2>Noticias y experiencias <span>que generan impacto.</span></h2><div className="corp-news-grid">{news.map((item)=><article key={item.href}><span>{item.category}</span><h3>{item.title}</h3><p>{item.excerpt}</p><a href={item.href}>Leer noticia <CtaIcon>↗</CtaIcon></a></article>)}</div></section>
    <section className="corp-contact" id="contacto"><div className="corp-shell"><p className="corp-eyebrow">Hablemos</p><h2>Potenciemos el talento de <span>tu organización.</span></h2><a className="corp-button" href="mailto:contacto@adconsulting.cl">Contáctanos <CtaIcon /></a></div></section>
    <CorporateFooter />
  </main>;
}
