import { Ad50Logo, CtaIcon, news } from "../shared";
import { CorporateFooter, CorporateHeader } from "./corporate-shell";

const services = [
  ["01", "Head Hunting", "Perfiles directivos y ejecutivos para los desafíos críticos de tu organización."],
  ["02", "Reclutamiento y Selección", "Procesos completos para conectar cada posición con las personas adecuadas."],
  ["03", "Liderazgo y Coaching", "Desarrollo de líderes y equipos mediante soluciones basadas en evidencia."],
  ["04", "Outplacement", "Acompañamiento responsable en transiciones y recolocación profesional."],
  ["05", "Capacitaciones", "Programas e-learning, b-learning y presenciales ajustados a cada necesidad."],
  ["06", "Plataforma AD+50", "Empleabilidad, formación e integración intergeneracional del talento senior."],
];

export default function Corporativa() {
  return <main className="corp-site">
    <CorporateHeader />
    <section className="corp-hero" id="inicio"><div className="corp-shell"><p className="corp-eyebrow">Gestión de talento</p><div className="corp-lead"><h1>Seleccionamos y potenciamos el talento de <span>tu empresa.</span></h1><div><p>Más de 14 años acompañando a organizaciones en Head Hunting, selección, outplacement, capacitación y coaching ejecutivo.</p><a className="corp-button" href="#servicios">Conoce nuestros servicios</a></div></div><div className="corp-team"><div><span>Somos AD Consulting</span><b>Personas que potencian personas</b></div><img src="/equipo-ad-consulting.jpg" alt="Equipo completo de AD Consulting" /></div><div className="corp-proof"><p><strong>+14 años de experiencia</strong></p><p><strong>+100 empresas impactadas</strong></p><p><strong>Cobertura nacional</strong></p></div></div></section>
    <section className="corp-video-section" aria-labelledby="corp-video-title"><div className="corp-shell"><div className="corp-video-heading"><p className="corp-eyebrow">Conoce AD Consulting</p><h2 id="corp-video-title">Personas que potencian <span>personas.</span></h2></div><div className="corp-video-frame"><video controls muted playsInline preload="metadata" poster="/video-ad-consulting-poster.webp" aria-label="Video corporativo de AD Consulting"><source src="https://www.adconsulting.cl/video_ad_2025.mp4" type="video/mp4" />Tu navegador no soporta la reproducción de video.</video></div></div></section>
    <section className="corp-services corp-shell" id="servicios"><p className="corp-eyebrow">Lo que hacemos</p><h2>Soluciones que conectan estrategia, personas y <span>resultados.</span></h2><div className="corp-service-grid">{services.map(([number,title,text])=><article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p><a href="/corporativa/servicios">Conocer más <CtaIcon /></a></article>)}</div></section>
    <section className="corp-intro corp-shell" id="nosotros"><div><p className="corp-eyebrow">AD Consulting</p><h2>Talento adecuado para <span>cada desafío.</span></h2></div><div><p>Somos un socio estratégico en gestión de personas. Comprendemos las necesidades de cada organización y diseñamos soluciones a la medida para fortalecer sus equipos.</p><p>Nos ocupamos del proceso con criterio, cercanía y una red diversa de profesionales.</p><a className="corp-text-link" href="/corporativa/nosotros">Conoce a nuestro equipo <CtaIcon /></a></div></section>
    <section className="corp-routes"><div className="corp-shell"><p className="corp-eyebrow">¿Qué necesitas?</p><h2>Un punto de entrada para <span>cada persona.</span></h2><div className="corp-route-grid"><article><span>Para las Empresas</span><h3>Busco talento para mi organización</h3><p>Selección, liderazgo, transición laboral y capacitación.</p><a href="/corporativa/servicios">Explorar servicios <CtaIcon /></a></article><article><span>Para las Personas</span><h3>Busco una nueva oportunidad</h3><p>Conoce el proceso y las ofertas actualmente disponibles.</p><a href="https://adconsulting.trabajando.cl/">Ver ofertas <CtaIcon /></a></article><article><span>Para los Equipos</span><h3>Quiero capacitar a mi organización</h3><p>Programas flexibles desarrollados por una OTEC reconocida por SENCE.</p><a href="/corporativa/servicios">Conocer capacitaciones <CtaIcon /></a></article></div></div></section>
    <section className="corp-platform" id="ad50"><div className="corp-shell"><div><p className="corp-eyebrow">Una plataforma de AD Consulting</p><Ad50Logo /><h2>La experiencia se activa con <span>oportunidades reales.</span></h2><p>Conecta talento senior y organizaciones a través de empleabilidad, formación, reclutamiento e integración generacional.</p><a className="corp-button" href="/corporativa/ad50">Conocer AD+50 <CtaIcon /></a></div><img src="https://ad50.adconsulting.cl/images/ad50-quienes-somos-equipo.webp" alt="Profesionales de distintas generaciones colaborando" /></div></section>
    <section className="corp-news corp-shell" id="actualidad"><p className="corp-eyebrow">Actualidad AD Consulting</p><h2>Noticias y experiencias <span>que generan impacto.</span></h2><div className="corp-news-grid">{news.map((item)=><article key={item.href}><span>{item.category}</span><h3>{item.title}</h3><p>{item.excerpt}</p><a href={item.href}>Leer noticia <CtaIcon>↗</CtaIcon></a></article>)}</div></section>
    <section className="corp-contact" id="contacto"><div className="corp-shell"><p className="corp-eyebrow">Hablemos</p><h2>Potenciemos el talento de <span>tu organización.</span></h2><a className="corp-button" href="mailto:contacto@adconsulting.cl">Contáctanos <CtaIcon /></a></div></section>
    <CorporateFooter />
  </main>;
}
